### ISSUE TITLE
Little modifications for Linux users [DONE]

### ISSUE THREAD

**Issue by LCIJ** [Ghost6446/Onlyfans-scrapper#1]
Hi! There is two modifications to make in code for Linux users, specifically in util/Driver.py :

1) In line 22, the **os.system("TASKKILL /IM chrome.exe /F")** have to be changed by **os.system("kill -9 chrome.exe")**
2) In line 23, the **os.system("CLS")** have to be changed by **os.system("clear")**

The rest is working nicely, thank you for the code. If you can find a way to download the media files that are sent through messages (either free or unlocked), it would be fantastic.

Cheers!

**Comment by Ghost6446** [comment]
this week i will update all.

**Comment by Ghost6446** [comment]
i try but for the moment there is no way to scroll page of message to the top, i try with request but there some key in headers that i cant get from the browser, do you know how i cant fix that problem ?

**Comment by Ghost6446** [comment]
> 

only solution is to manual scroll to the top of the page
