### ISSUE TITLE
Need help for beginner, many thanks

### ISSUE THREAD

**Issue by diephoang2001** [Ghost6446/Onlyfans-scrapper#12]
After I press y and n, then close all instance of chrome, after that just load home page only. Nothing happend , really need help,
 Thank you
![image](https://github.com/Ghost6446/Onlyfans-scrapper/assets/137526571/8181514b-560b-4e99-8879-922f202f788b)

**Comment by Ghost6446** [comment]
You need to insert pass in usern in login in the page open.
