### ISSUE TITLE
Error during log-in attempt

### ISSUE THREAD

**Issue by greyhat94** [Ghost6446/Onlyfans-scrapper#13]
Hello again. I need your help. I've recently downloaded the latest version of your repository and installed all the requirements needed. However, when I try to perform the login, I got this error: 

```
Traceback (most recent call last):
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.0\Run.py", line 47, in <module>
    main()
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.0\Run.py", line 21, in main
    generate()
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.0\Src\Util\Generator\generate_headers.py", line 24, in generate
    driver.create(False, False)
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.0\Src\Util\Helper\driver.py", line 51, in create
    self.driver = webdriver.Chrome(options=self.options,  service=self.service)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
Stacktrace:
        GetHandleVerifier [0x00FA6EE3+174339]
        (No symbol) [0x00ED0A51]
        (No symbol) [0x00BE6FF6]
        (No symbol) [0x00C0D809]
        (No symbol) [0x00C0B3F3]
        (No symbol) [0x00C07A0F]
        (No symbol) [0x00C3E259]
        (No symbol) [0x00C3DBBA]
        (No symbol) [0x00C36DA6]
        (No symbol) [0x00C11034]
        (No symbol) [0x00C11F8D]
        GetHandleVerifier [0x01044B1C+820540]
        sqlite3_dbdata_init [0x011053EE+653550]
        sqlite3_dbdata_init [0x01104E09+652041]
        sqlite3_dbdata_init [0x010F97CC+605388]
        sqlite3_dbdata_init [0x01105D9B+656027]
        (No symbol) [0x00EDFE6C]
        (No symbol) [0x00ED83B8]
        (No symbol) [0x00ED84DD]
        (No symbol) [0x00EC5818]
        BaseThreadInitThunk [0x765D7BA9+25]
        RtlInitializeExceptionChain [0x774DBD2B+107]
        RtlClearBits [0x774DBCAF+191]
```
I rely on your help and look forward to hearing from you soon. Thanks so much.

**Comment by Ghost6446** [comment]
Install chrome

**Comment by greyhat94** [comment]
> Install chrome

I've already installed Chrome.

**Comment by Ghost6446** [comment]
Have you install all requirements ?

**Comment by greyhat94** [comment]
> The script open a google page ?

No, it didn't.

**Comment by Ghost6446** [comment]
I think the problem is selenium wire, try install older version. Pip install selenium-wire== and after that use the same comand but with a version after ==

**Comment by greyhat94** [comment]
> I think the problem is selenium wire, try install older version. Pip install selenium-wire== and after that use the same comand but with a version after ==

And what are the respective selenium ones to install?

**Comment by greyhat94** [comment]
I've tried the new version. Once I try to perform the login, Google Chrome opened and closed it instantly by itself, and I get this output on my terminal: 

```
Do you want to auto generare headers file? (With login): y
Have you already logged in ?: n
[13:41:35] LOAD HOME PAGE                                                                                                     generate_headers.py:17
           Cant get url: https://onlyfans.com/                                                                                          driver.py:56
PS C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.0> 


```

**Comment by Ghost6446** [comment]
CHANGE:

def close_chrome_instances(self):
        if platform.startswith("linux"):
            try: subprocess.check_output("pkill -f chrome", shell=True)
            except: pass

        elif platform == "win32":
            try: subprocess.check_output("TASKKILL /IM chrome.exe /F", shell=True, creationflags=0x08000000)
            except: pass


WITH:

def close_chrome_instances(self):
        print("")

IN:  "main/Src/Util/Helper/driver.py"

**Comment by Ghost6446** [comment]
I think close all chrome in your pc take too much time that it close driver page

**Comment by greyhat94** [comment]
Therefore, the code should appear in this way: 

```
def close_chrome_instances(self):
print("")
try: subprocess.check_output("pkill -f chrome", shell=True)
except: pass

    elif platform == "win32":
        try: subprocess.check_output("TASKKILL /IM chrome.exe /F", shell=True, creationflags=0x08000000)
        except: pass
```

Is that correct?

**Comment by Ghost6446** [comment]
only that 

def close_chrome_instances(self):
	print("")


in this way, it will not try to close chrome.

**Comment by greyhat94** [comment]
> only that
> 
> `def close_chrome_instances(self): print("")`
> 
> in this way, it will not try to close chrome.

Hi again. Thank you for your prompt answer. I have tried editing the script, but I've got this error: 

T```
raceback (most recent call last):
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.1\Run.py", line 5, in <module>
    from Src.Util.Generator.generate_headers import generate, make_login
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.1\Src\Util\Generator\generate_headers.py", line 4, in <module>
    from Src.Util.Helper.driver import Driver
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.1\Src\Util\Helper\driver.py", line 15
    if platform.startswith("linux"):
IndentationError: unexpected indent
PS C:\Users\umile\Desktop\Tools\OnlyFans Scraper 9.1> 

```

Did I make something wrong with editing the script? I rely on your help and look forward to hearing from you sooner.

**Comment by Ghost6446** [comment]
You need to delete all after print(""), only in this function

**Comment by greyhat94** [comment]
![image](https://github.com/Ghost6446/Onlyfans-scrapper/assets/113683805/55846d21-a4cb-45b6-bf93-8e785110754b)

I keep on experiencing the same issue. Did I make the changes correctly?

**Comment by Ghost6446** [comment]
Yes not it is right

**Comment by Ghost6446** [comment]
Try change the script name folder and delete space like only_v_0.9

**Comment by greyhat94** [comment]
> Yes not it is right

Therefore, I've made some mistakes into editing the script?

**Comment by Ghost6446** [comment]
no no, now it doesnt try to close chrome

**Comment by greyhat94** [comment]
> no no, now it doesnt try to close chrome

I will try to run the script again and let you know if I continue to experience the same issue.

**Comment by Ghost6446** [comment]
Ok

**Comment by Yash5198** [comment]
> Ok

Hii I tried to use this but after first login and then opening second time the browser closes automatically what to do after that ?

**Comment by Ghost6446** [comment]
It is normal if close without login now, the most import part is that something lile save .json

**Comment by Yash5198** [comment]
So what should I do now ?

**Comment by Yash5198** [comment]
![Screenshot 2024-01-11 214304](https://github.com/Ghost6446/Onlyfans-scrapper/assets/67137293/ae0f2020-ec78-4c8f-a7c8-39f5d387d830)

**Comment by Ghost6446** [comment]
Run it, if it all rigth pass n if you want to generate headers and go.

**Comment by Yash5198** [comment]
it shows error when i run generate headers file it shows src module not found

**Comment by Yash5198** [comment]
which file should i run after running run.py ?

**Comment by Yash5198** [comment]
it shows error 403

**Comment by Ghost6446** [comment]
Allora il file json è sbagliato

**Comment by Yash5198** [comment]
Come posso correggerlo e dove è presente?

**Comment by Yash5198** [comment]
{
  "user-agent": "",
  "app-token": "",
  "accept": "",
  "x-bc": "",
  "accept-encoding": "",
  "accept-language": "",
  "user-id": "",
  "cookie": ""
}
JSON file

**Comment by Ghost6446** [comment]
Voul dire che non ha creato nulla, a sto punto non  lo so prova su un altro pc

**Comment by greyhat94** [comment]
![image](https://github.com/Ghost6446/Onlyfans-scrapper/assets/113683805/d90d7acc-32fb-4246-b4b9-46d8743d1334)

I've edited the code as you've requested. However, I keep on experiencing the same issue. Google Chrome opens and closes immediately on its own. I have several profiles on Chrome, so I'd like to know how to avoid getting this incovenience. Thank you again for your kindness.

**Comment by Ghost6446** [comment]
Is normal if close, but create a valido json and not some error.

**Comment by greyhat94** [comment]
Therefore, how can I avoid getting this issue? Thanks again for your
patience and kindness.

Il gio 11 gen 2024, 21:42 Ghost ***@***.***> ha scritto:

**Comment by Ghost6446** [comment]
For the moment idk, i dont have you wr pc to test with, if out can try abother pc
