### ISSUE TITLE
Variable 'user-agent' is empty

### ISSUE THREAD

**Issue by jincanna** [Ghost6446/Onlyfans-scrapper#16]
Checking github version ...
=> Everything up to date
=> Last version: v0.9.3

Onlyfans-scrapper was downloaded 6 times, but only 550.0% of You(!!) have starred it.
        Help the repository grow today, by leaving a star and sharing it to others online!

Checking json file ...
Variable 'user-agent' is empty.
[14:55:24] Json file is not valid (retry generator)                                                            run.py:42

I tried to try this but got this warning. I don't know what to do.

**Comment by Ghost6446** [comment]
Today i will check why, doesnt captire user agent, to bypass this search user agent browser and copy that to json file

**Comment by Ghost6446** [comment]
Try if now is fix
