### ISSUE TITLE
Wrong headers issue

### ISSUE THREAD

**Issue by jincanna** [Ghost6446/Onlyfans-scrapper#17]
The existing issue has been resolved. However, a new problem has occurred.

Do you want to auto generate headers file? (With login): y
Have you already logged in ?: y

[04:38:35] Closing chrome ...                                                                               driver.py:21
[04:38:38] Load home page                                                                         generate_headers.py:25
[04:38:54] Wrong headers                                                                          generate_headers.py:59
           Close driver                                                                                     driver.py:64

I am using Python 3.9.13 and Chrome. I followed the default process with

Do you want to auto generate headers file? (With login): y
Have you already logged in ?: n

What possible solutions can I try?"

**Comment by Ghost6446** [comment]
Han but you log in in the home page load ?

**Comment by jincanna** [comment]
I'm sorry for the late response.

The wrong header error occurs a few seconds after the home page is opened.

**Comment by Ghost6446** [comment]
You need to press y when ask have you log in.

**Comment by Ghost6446** [comment]
> I'm sorry for the late response.
> 
> The wrong header error occurs a few seconds after the home page is opened.

Now work ?

**Comment by jincanna** [comment]
Maybe I'll have to reinstall it. I'll try everything possible and let you know again. Thank you for your care
