### ISSUE TITLE
Chat download bypass

### ISSUE THREAD

**Issue by moamelmoh** [Ghost6446/Onlyfans-scrapper#18]
What does it mean do you want to download from the chat? What does it mean, choose ID, choose a user, and how to use the code

**Comment by Ghost6446** [comment]
this -> "Do you want to download media from a chat", basically download image and video from a chat with a user

**Comment by moamelmoh** [comment]
So how do I download videos from a creator and not a chat?

**Comment by Ghost6446** [comment]
write n and continue

**Comment by moamelmoh** [comment]
What do I write when he says Select a person?

**Comment by Ghost6446** [comment]
nothing use key arrow and select one

**Comment by moamelmoh** [comment]
![Screenshot 2024-02-04 202827](https://github.com/Ghost6446/Onlyfans-scrapper/assets/157844512/704b7ba0-aef2-4951-8f88-d97d538a9b7b)

**Comment by moamelmoh** [comment]
There are no options

**Comment by Ghost6446** [comment]
because you dont follow anyone

**Comment by moamelmoh** [comment]
I thought that this scraper would enable me to download content for free

**Comment by Ghost6446** [comment]
Yes, or download private you if you pay for view.
