### ISSUE TITLE
Error using on.get_chat()

### ISSUE THREAD

**Issue by vinbergg** [Ghost6446/Onlyfans-scrapper#3]
getting some errors using the chat scrapper 
"TypeError: string indices must be integers, not 'str'

Very new to this code thing so apologize if its an easy solo fix :)

**Comment by Ghost6446** [comment]
yes, no problem, can you copy paste your run.py ?

**Comment by Ghost6446** [comment]
if the chat is like that "https://onlyfans.com/my/chats/chat/304963869/" the command is  on.get_chat("304963869")

**Comment by vinbergg** [comment]
Traceback (most recent call last):
  File "Run.py", line 4, in <module>
    on.get_chat("353174843")
  File only.py", line 345, in get_chat
    download_chat(
  File "only.py", line 224, in download_chat
    dump_chat(msg['media'])
              ~~~^^^^^^^^^

get this error now instead

**Comment by Ghost6446** [comment]
try now
