### ISSUE TITLE
Ubuntu - No module named 'seleniumwire.utils'

### ISSUE THREAD

**Issue by Buhos-Dev** [Ghost6446/Onlyfans-scrapper#4]
Traceback (most recent call last):
  File "/home/buhosdev/BigData/Onlyfans-scrapper/Run.py", line 1, in <module>
    from Only.only import Main
  File "/home/buhosdev/BigData/Onlyfans-scrapper/Only/only.py", line 10, in <module>
    from seleniumwire.utils import decode
ModuleNotFoundError: No module named 'seleniumwire.utils'

**Comment by Ghost6446** [comment]
pip install selenium-wire

**Comment by Buhos-Dev** [comment]
In fact, I installed all the libraries and it still gives me the same error, I am using Ubuntu 23

**Comment by Ghost6446** [comment]
what is the versione of python ?

**Comment by Buhos-Dev** [comment]
Python 3.11.5

**Comment by Ghost6446** [comment]
try with 3.9
