### ISSUE TITLE
No module named only.util

### ISSUE THREAD

**Issue by mrW0RLDWlDE** [Ghost6446/Onlyfans-scrapper#9]
New update gives me this error

ModuleNotFoundError: No module named 'Only.util.driver'

also im not sure how to use new gui

**Comment by SirSolrac** [comment]
I am also getting this error

**Comment by Ghost6446** [comment]
Check new version and new mp4 test

**Comment by mrW0RLDWlDE** [comment]
after running "python .\Run.py" still getting same error message

 File "C:\Users\*****\Downloads\Onlyfans-scrapper-main\Onlyfans-scrapper-main\Run.py", line 5, in <module>      
    from Only.only import Main
  File "C:\Users\*****\Downloads\Onlyfans-scrapper-main\Onlyfans-scrapper-main\Only\only.py", line 4, in <module>
    from Only.util.driver import Driver
ModuleNotFoundError: No module named 'Only.util.driver'

**Comment by Ghost6446** [comment]
Retry now

**Comment by mrW0RLDWlDE** [comment]
Still same issue

**Comment by Ghost6446** [comment]
New version work

**Comment by SirSolrac** [comment]
Can confirm the new version is now working for me. Thanks!

**Comment by mrW0RLDWlDE** [comment]
Old issue was fixed but now im receiving "No module named 'pkg_resources'", sorry that it seems like this is an unending issue but im hoping to be able to fix it soon

**Comment by mrW0RLDWlDE** [comment]
nvm i found solution. thanks for fixing previous issue

**Comment by Ghost6446** [comment]
Perfect
